DROP TABLE IF EXISTS product_store;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS STORE;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS seq;

CREATE TABLE USER (
	ID BIGINT(20) NOT NULL,
	PASSWORD VARCHAR(64),
	USERNAME VARCHAR(64) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE STORE (
    ID BIGINT(20) NOT NULL,
    USER_ID BIGINT(20),
    NAME VARCHAR(64),

    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE PRODUCT(
    ID BIGINT(20) NOT NULL,
    NAME VARCHAR(64),

    PRIMARY KEY (ID)
);

CREATE TABLE product_store(
    STORE_ID BIGINT(20),
    PRODUCT_ID BIGINT(20),

    PRIMARY KEY (STORE_ID, PRODUCT_ID),
    FOREIGN KEY (STORE_ID) REFERENCES STORE(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);

CREATE TABLE seq (
	next_val BIGINT(20) DEFAULT NULL
) ENGINE = InnoDB
DEFAULT CHARSET = utf8;
INSERT INTO SEQ(next_val) value (1234);
