DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS seq;

CREATE TABLE USER (
	ID BIGINT(20) NOT NULL,
	PASSWORD VARCHAR(64),
	USERNAME VARCHAR(64) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE seq (
	next_val BIGINT(20) DEFAULT NULL
) ENGINE = InnoDB
DEFAULT CHARSET = utf8;
INSERT INTO SEQ(next_val) value (1234);
